## Strings (`str`)
Strings are immutable sequences of characters. They support indexing and slicing.

In [54]:
# Note that I intentionally did not include any comments. You should add comments to explain the code.
# Your assignment includes adding comments to all code cells.
text = "Engineering" #assigns str to var 'text'
print("First character:", text[0]) # Each character is indexed, starting from 0.
print("Slice:", text[1:5]) # Prints the str prints the 1st to 4th letter in the str 'text' stops at 5th

# Your code here to print out diffent characters and slices of the string.
name = 'Cole'
print(name[1]) # Prints the letter in the 1st str slot

First character: E
Slice: ngin
o


## Lists (`list`) [ ]
Lists are ordered and mutable collections. They can contain mixed types and be nested.

In [55]:
data = [1, "temp", [3.5,4.5, 1.2, 4 , "green"]] # You should change the nested array to 5 elements.
print(type(data)) # Checks classification of variable
print("Second element:", data[1]) # Prints item in list slot 1
print("Nested list:", data[2]) # Do you need to change anything on this line? Why or why not? No it gives us the list
print("Second element in the nested list:", data[2][2]) # What do you expect to see? expect to see the 3rd item in the nested list

<class 'list'>
Second element: temp
Nested list: [3.5, 4.5, 1.2, 4, 'green']
Second element in the nested list: 1.2


## Tuples (`tuple`) ( )
Tuples are ordered and immutable collections.

In [56]:
point = (3, 4, 5)
print("X coordinate:", point[0])
# Your code here to print out different elements of the tuple.i.e, the Y or Z element.

X coordinate: 3


## Sets (`set`) { }
Sets are unordered collections of unique elements.

In [57]:
sensors = {"temp", "pressure", "temp", "length", "weight"} # Add more elements to the set.
print("Set contents:", sensors)
print("Is 'temp' in sensors?", "temp" in sensors)
# Note that sets are unordered. You cannot access elements by index.
# Your code here to add more elements and check membership of other elements.

Set contents: {'length', 'pressure', 'temp', 'weight'}
Is 'temp' in sensors? True


## Dictionaries (`dict`) { "key1":, "key2": .....}
Dictionaries store key-value pairs and allow fast lookup using keys.

In [58]:
sensor_data = {"temp": 22.5, "pressure": 101.3, "Work": 200} # Add more key-value pairs to the dictionary.
print("Temperature:", sensor_data["temp"])
# Your code here to print out different values using their keys and add new key-value pairs.
print(sensor_data)
print(sensor_data['Work'])

Temperature: 22.5
{'temp': 22.5, 'pressure': 101.3, 'Work': 200}
200


### Example- 🛒 Grocery Bill Calculator

Loop through a list of grocery items and their prices shown in the code. Calculate the total bill. Apply a 5% discount if the total exceeds $50. Print out the total bill and an indication on whether a discount is applied. 

Hint: You will need a for loop through this list and then a conditional statement to determine if a discount can be applied. 

In [59]:
items = {'Milk': 4.5, 'Bread': 3.2, 'Eggs': 6.0, 'Cheese': 8.5, 'Fruits': 12.0, 'Vegetables': 10.0, 'Snacks': 9.0, 'Beverages': 7.5}
# You can add/delete items if you want
total = 0.0
total_item = 0

# Iterate through items and sum prices
for name, price in items.items():
    total += price #adds price of items in list to the total price
    total_item += 1 #counts per item the number of items in the "grocery cart"
    print(f"{name} costs ${price:.2f}")

# Your code here
if total > 50: # if the total is more than $50
    discount = total * 0.05 # discount calculation
    print(f"Discount applied: ${discount:.2f}")
    total -= discount # subtracts the discount from the total cost
    
print(f"Total grocery bill is ${total:.2f} for {total_item} items.") # prints result


Milk costs $4.50
Bread costs $3.20
Eggs costs $6.00
Cheese costs $8.50
Fruits costs $12.00
Vegetables costs $10.00
Snacks costs $9.00
Beverages costs $7.50
Discount applied: $3.04
Total grocery bill is $57.67 for 8 items.


## NumPy Arrays (`np.array( )`)
NumPy arrays are efficient for numerical data and support vectorized operations. Here is a simple example. We will dicsuss how to use NumPy Arrays more in future lectures. 

In [60]:
import numpy as n # imports module
arr1 = n.array([1, 2, 3]) # 1 x 3 array
arr2 = n.array([[4, 5],  # 2 x 2 array
                 [7, 8]])
print("Second element of arr1 multiplied by 2:", arr1[1]*2) # array 1 * 2
print("Array 2:") # prints 'array 2: :' 
print(arr2) # actually prints array

Second element of arr1 multiplied by 2: 4
Array 2:
[[4 5]
 [7 8]]


In [61]:
# Your code here to print out a 5 x 3 numpy array and the entire array multiplied by 2.

import numpy as np 

arr3 = np.array([[1, 2, 3,], 
                [4, 5, 6,],
                [7, 8, 9,],
                [10, 11, 12],
                [13, 14, 15]])
print(arr3) # prints numpy array
print(arr3*2) #prints the matrix *2


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]
 [26 28 30]]


## Sorting
Python lists can be sorted using the built-in `sorted()` function or the `.sort()` method.

In [62]:
numbers = [5, 2, 9, 1, 5, 6] # list of numbers
print("Original:", numbers) # prints the list

numbers.sort() # sorts the numbers in order from least to greatest
sorted_numbers = sorted(numbers) # uncomment this line if you want to use sorted() instead of sort()
# sorted() is usted on iretables (lists, tuples, strings,etc.)

print("Sorted:  ", numbers)
print("Sorted:  ", sorted_numbers) # when you uncomment sorted_numbers

Original: [5, 2, 9, 1, 5, 6]
Sorted:   [1, 2, 5, 5, 6, 9]
Sorted:   [1, 2, 5, 5, 6, 9]


In [63]:
# Your code here
# Make up a list (any type you want) and sort them. Print out the original and sorted lists.
list = (1 ,2 ,4 ,3 ,7 ,1 ,5.6 )
sorted = sorted(list)
print(f"Original List: {list}")
print(f"Sorted List: {sorted}")
# You can only use sorted() function 

Original List: (1, 2, 4, 3, 7, 1, 5.6)
Sorted List: [1, 1, 2, 3, 4, 5.6, 7]


In [64]:
# Your code here
# Make up a list (any type you want) and sort them. Print out the original and sorted lists.
# You can only use .sort() method.

list = [1, 2, 4, 3, 7, 1, 5]
print(f"Original List: {list}")

list.sort() # reassigns list as sorted list
print(f"Sorted List: {list}")


Original List: [1, 2, 4, 3, 7, 1, 5]
Sorted List: [1, 1, 2, 3, 4, 5, 7]


### Sort a list of tuples usign a *lambda* function
A `lambda` function in Python is an anonymous, single-expression function. It is defined using the `lambda` keyword and allows for the creation of small, inline functions without needing to use the def keyword or assign a name. `lambda` functions are particularly useful in situations where a small, one-off function is needed as an argument to a higher-order function (a function that takes other functions as arguments). We will discuss more in future lectures. 

In [65]:
my_list = [(1, 'apple'), (2, 'orange'), (3, 'banana'), (1,'avacado')] # List of tuples
my_list.sort(key= lambda item: item[0]) # Sorts by the first element of each tuple
print("Sorted by first element:", my_list)
# You should change the list an print out the sorted list based on different elements.

Sorted by first element: [(1, 'apple'), (1, 'avacado'), (2, 'orange'), (3, 'banana')]


In [ ]:
del sorted # gets rid of sorted variable in a previous code thread - credit to chatgtp

# Your code here.  
# Make up a list of tuples (anything you want) and sort them. 
pets = [(5, "Mo Mo"), (18, "Mei Mei"), (3, "Bao")] # yes my real pets!
pets_age = sorted(pets, key=lambda item: item[0]) # sorts my tuple by the first element

print("Original:", pets)
print("Sorted by age:", pets_age)

Original: [(5, 'Mo Mo'), (18, 'Mei Mei'), (3, 'Bao')]
Sorted by age: [(3, 'Bao'), (5, 'Mo Mo'), (18, 'Mei Mei')]


### Sorting Dictionaries by Values
Need to use `sorted()` with a `lambda` function to sort *dictionary* items by value. Cannot use `.sort`

In [ ]:
grades = {'Alice': 88, 'Bob': 95, 'Charlie': 78} # dictionary items
sorted_grades = sorted(grades.items(), key=lambda x: x[1]) # sorting by second element
print("Sorted by value:", sorted_grades) # prints sorted dictionary

Sorted by value: [('Charlie', 78), ('Alice', 88), ('Bob', 95)]


In [80]:
# Your code here
# Make up an array of dictionary items (any type you want) and sort them.
pets = {'Mo Mo': 5, 'Mei Mei': 18, 'Bao': 3}
pets_age = sorted(pets.items(), key = lambda x: x[1])
# Print out the original and sorted lists.
print("Sorted by age: ", pets_age)

Sorted by age:  [('Bao', 3), ('Mo Mo', 5), ('Mei Mei', 18)]


## TXT Files


### Write a TXT file

The code below creates a text file called *test.txt* and write a couple lines in it. 
Check and see where this file is located on your desk!

In [82]:
f = open('test.txt', 'w') # opened a file object *f* with the file name 'test.txt'; "w+" for the mode indicates write
for i in range(5):
    f.write(f"This is line {i+1}\n") #write 5 lines. Note the newline '\n' at the end of the string.
    
f.close() # It is good practice to close the file using f.close() in the end.

# Check your local folder and see whether the file 'test.txt' is created and contains the 5 lines.

## Append to a TXT file
We can also append some string to the *test.txt* file. It is very similar to how we write the file, with only one difference - change the mode to 'a' instead. 

In [70]:
f = open('test.txt', 'a')
f.write(f"This is another line\n") #append a line
# Try to add more lines 
f.close()
# Check your local folder and see whether the file 'test.txt' is updated with the new line.
# Append more lines as needed.

## Reading a TXT File
Let's read in the *test.txt* file we created above and store all the contents in the file to a variable *content*.

In [71]:
# Add comments to explain the code.
f = open('./test.txt', 'r')
content = f.read()
f.close()
print(content)

This is line 1
This is line 2
This is line 3
This is line 4
This is line 5
This is another line



In [72]:
# Another way to read a file using 'with' statement
with open('test.txt', 'r') as f: 
    content = f.read()
f.close()
print(content)

This is line 1
This is line 2
This is line 3
This is line 4
This is line 5
This is another line



In [73]:
# Try to generate a new TXT file and write some data into it.
# Your code here

In [74]:
# Try to read the TXT file you just created and print out the content.
# Your code here

## Dealing with numbers and arrays

Since we are working with numerical methods later, and many times, we work with the numbers or arrays. We could use the above methods to save the numbers or arrays to a file and read it back to the memory. But it is not so convenient this way. Instead, commonly we use the *numpy* package to directly save/read an array. For example, you can use np.savetxt & np.loadtxt as shown below. 


In [75]:
# Store an array to a file named *my_arr.txt* 
# and read it back to a variable called *my_arr*. 
import numpy as np
arr = np.array([[1.25, 2.21, 3.05], 
                [4.13, 5.75, 6.92]]) # Use np.array to create the array.
np.savetxt('my_arr.txt', arr, fmt='%.2f') #Save the array to a text file w/format and headers specified
my_arr = np.loadtxt('my_arr.txt')
print(my_arr)
# See whether the file 'my_arr.txt' is created in your local folder.

[[1.25 2.21 3.05]
 [4.13 5.75 6.92]]


In [76]:
# Try to make a 3x3 matrix using np.array and save it to a file named *my_matrix.txt*.
# Then read it back to a variable called *my_matrix* and print it out.


## Write and open a CSV file
CSV files store tabular data. Useful for lists, dictionaries, and arrays.
A simple example of using the random number generator to generate 100 rows and 5 columns of data 

In [77]:
import numpy as np
data = np.random.random((100,3))
np.savetxt('test.csv', data, fmt = '%.2f', delimiter=',', header = 'c1, c2, c3')
# See whether the file 'test.csv' is created in your local folder.

## Read a CSV File
### Use *np.loadtxt* function
We could read in the csv file using the *np.loadtxt* function. Let's read in the csv file we just saved to the disk to a variable *my_csv*, and output the first 5 rows. Note here we use the *delimiter* again to specify that the data in the file is separated by commas. 

In [78]:
my_csv = np.loadtxt('./test.csv', delimiter=',')
my_csv[:10]

array([[0.54, 0.51, 0.42],
       [0.1 , 0.82, 0.33],
       [0.38, 0.92, 0.81],
       [0.28, 0.13, 0.7 ],
       [0.01, 0.5 , 0.66],
       [0.16, 0.75, 0.79],
       [0.37, 0.67, 0.17],
       [0.33, 0.98, 0.76],
       [0.75, 0.6 , 0.22],
       [0.38, 0.9 , 0.93]])

### Use *np.genfromtxt* to read the file and print out the data.

In [79]:
# Download the example.csv file from Canvas and put it in your local folder.
# Data include: Name (string), Age (int), City (string)
import numpy as np
data = np.genfromtxt('example.csv', delimiter=',', names=True, dtype=None, encoding='utf-8')
# print(data) # Data contains names, ages and cities.
ages = data['Age']
print("Ages:", ages)
# Your code here to read the file and print out the data other than the "Age" column.

FileNotFoundError: example.csv not found.

### Sort data in CSV file and write the sorted data in a new CVS file

In [ ]:
# Try to add more lines of data to example.csv by hand and sort the data based on age.

# Sort data based on ages (descending)
sorted_data = np.sort(data, order='Age')[::-1]
print(sorted_data)

# Header for the CSV file
header = 'Name, Age, City'

# Save the structured array to CSV.
# Use one format specifier per field in the structured array: Name (string), Age (int), City (string).
# Provide fmt as a list so the number of formats matches the number of columns.
np.savetxt('sorted_examples.csv', sorted_data, fmt=['%s','%d','%s'], delimiter=',', header=header, comments='')

In [ ]:
# Use the random data generation code to create a CSV file of 100 data, between 0 to 1000. 
# Sort them and write them to a new "sorted" CSV file.
# You need to upload the original CSV file and the sorted CSV file. 